### ISSUE TITLE
Banner gets duplicated on user/edit page

### ISSUE THREAD

**Issue by jlazerus** [2016SoftwarePractices/Encryptomail#32]
To replicate this issue, go to your user page then click the "Edit User" button. Here's is what mine looks like: 
![encryptomail2banners](https://cloud.githubusercontent.com/assets/2712322/13414769/5e0adf48-df12-11e5-9d3f-33b10b940eae.jpg)

Mac OS X 10.10.5, Google Chrome Version 48.0.2564.116 (64-bit)

**Comment by Zeroff** [comment]
fixed it!
